In [2]:
import numpy as np

X = np.random.normal(loc=1, scale=10, size=(1000, 50))
print (X)

[[  7.39006478   7.30856471 -15.52478945 ...   4.08859074  17.69302265
    5.52818462]
 [ -5.31957929 -13.06514322   3.16326706 ...  11.43579192 -10.54741385
    7.2384589 ]
 [  5.87522813  -1.31965217  10.73091211 ... -17.06734511  -1.53005905
   12.2797432 ]
 ...
 [ 12.41368988   2.19908659  17.14867587 ...  -4.8902374   20.60620595
    5.15130564]
 [ 10.40479415  13.87467914 -18.05123333 ... -16.19346293  -3.96208425
   -9.24620644]
 [ 15.70529058  -0.13138985   3.49682547 ...   6.53542817   3.06879134
  -12.55010203]]


In [6]:
mean = np.mean(X, axis=0) #columns mean
std = np.std(X, axis=0) #columns standard deviation
X_norm = ( X - mean ) / std
print(mean)
print(std)
print(X_norm)

[0.46726337 1.00952759 0.44057781 0.98154941 1.30998    0.82305567
 1.33069508 1.22057683 0.97441852 1.62605081 1.11288785 1.32157254
 1.13254764 1.20137402 0.69342094 1.15615172 1.01711009 1.17746156
 1.410021   1.56892415 1.01574355 1.20266093 1.15388856 1.00042101
 1.31531426 1.2431497  1.47936519 1.0141291  1.02822609 0.85581055
 0.90226612 1.58574988 0.60262173 0.74797329 0.04664515 0.90622632
 0.82200841 0.65956112 0.72048353 0.68962933 1.23545245 0.61725513
 1.05529651 0.67765981 0.76200171 1.00539086 0.74574161 1.08167121
 1.04477163 1.03798159]
[ 9.89757089  9.88509402 10.16236202  9.87150054 10.05538042  9.83481769
  9.84338714  9.75665163  9.8840909   9.92596334 10.11411085  9.96385122
  9.8730505   9.8621142  10.01930241  9.86502325  9.97300199 10.06184424
  9.90628424  9.7541897  10.04076774  9.88799026  9.97447243  9.93423449
 10.26625069  9.9806006  10.30640538  9.96703338 10.07615712 10.16244264
 10.27623564  9.32823426  9.62487933 10.05206361  9.93787788 10.32112006
 1

In [13]:
Z = np.array([[4, 5, 0], 
             [1, 9, 3],              
             [5, 1, 1],
             [3, 3, 3], 
             [9, 9, 9], 
             [4, 7, 1]])



In [17]:
r = np.sum(Z, axis=0)
print (np.nonzero(r > 10))
print(r)

(array([0, 1, 2]),)
[26 34 17]


In [29]:
E1 = np.eye(3)
E2 = np.eye(3)
print(np.vstack((E1, E2)))
      

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [1]:
# titanic definitions
# run
import pandas
dataframe = pandas.read_csv('titanic.csv', index_col="PassengerId")

def writeFile(fName, data):
    with open(fName, 'w') as f:
        print(data, file=f, end='')
        
dataframe.head(13)

Survived  Pclass  \
PassengerId                     
1                   0       3   
2                   1       1   
3                   1       3   
4                   1       1   
5                   0       3   
6                   0       3   
7                   0       1   
8                   0       3   
9                   1       3   
10                  1       2   
11                  1       3   
12                  1       1   
13                  0       3   

                                                          Name     Sex   Age  \
PassengerId                                                                    
1                                      Braund, Mr. Owen Harris    male  22.0   
2            Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
3                                       Heikkinen, Miss. Laina  female  26.0   
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0   
5                                     Allen, Mr. William Henry    male  35.0   
6                                             Moran, Mr. James    male   NaN   
7                                      McCarthy, Mr. Timothy J    male  54.0   
8                               Palsson, Master. Gosta Leonard    male   2.0   
9            Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0   
10                         Nasser, Mrs. Nicholas (Adele Achem)  female  14.0   
11                             Sandstrom, Miss. Marguerite Rut  female   4.0   
12                                    Bonnell, Miss. Elizabeth  female  58.0   
13                              Saundercock, Mr. William Henry    male  20.0   

             SibSp  Parch            Ticket     Fare Cabin Embarked  
PassengerId                                                          
1                1      0         A/5 21171   7.2500   NaN        S  
2                1      0          PC 17599  71.2833   C85        C  
3                0      0  STON/O2. 3101282   7.9250   NaN        S  
4                1      0            113803  53.1000  C123        S  
5                0      0            373450   8.0500   NaN        S  
6                0      0            330877   8.4583   NaN        Q  
7                0      0             17463  51.8625   E46        S  
8                3      1            349909  21.0750   NaN        S  
9                0      2            347742  11.1333   NaN        S  
10               1      0            237736  30.0708   NaN        C  
11               1      1           PP 9549  16.7000    G6        S  
12               0      0            113783  26.5500  C103        S  
13               0      0         A/5. 2151   8.0500   NaN        S

In [31]:
# task 1: gender analysis  
import numpy as np

def countGender(gender):
    return len(dataframe[(dataframe.Sex == gender)]) 

writeFile('11.txt', str(countGender('male')) + ' ' + str(countGender('female') ))

In [16]:
# task 2: percentage of survived
dfLen = len(dataframe.index)
survivedLen = len( dataframe[dataframe.Survived == 1] )
writeFile('2.txt', round((survivedLen / dfLen ) * 100 , 2) )

In [15]:
# task 3: percentage of First Class passengers 
dfLen = len(dataframe.index)
firstClassLen = len(dataframe[dataframe.Pclass == 1])
writeFile('3.txt', round( ( firstClassLen / dfLen ) * 100, 2 ) )

In [72]:
# https://towardsdatascience.com/filtering-data-frames-in-pandas-b570b1f834b9
type(dataframe.Age)
HEAD = 5
def headDframe(df):
    return df.head(HEAD)
headDframe( dataframe[['Age', 'Name']] )
headDframe( dataframe.select_dtypes(include=np.number) )
headDframe( dataframe.select_dtypes(include='number') )
dataframe[['Age', 'Name']].dtypes
dataframe[['Age', 'Name']].info()
dataframe.index
dataframe.loc[2] # selecting series.Series
dataframe.loc[[2]] # selecting single row frame.DataFrame
dataframe.iloc[1, [2,3,4]]
dataframe.loc[3, ['Age', 'Ticket']]
dataframe.loc[2:5, ['Age', 'Ticket']]

<class 'pandas.core.frame.DataFrame'>
Int64Index: 891 entries, 1 to 891
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Age     714 non-null    float64
 1   Name    891 non-null    object 
dtypes: float64(1), object(1)
memory usage: 53.2+ KB


Age            Ticket
PassengerId                        
2            38.0          PC 17599
3            26.0  STON/O2. 3101282
4            35.0            113803
5            35.0            373450

In [34]:
# task 4: percentage of First Class passengers 
dfAge = dataframe[['Age']] # DataFrame of one column
# dfAge = dfAge.dropna() # cleaned from NaNs
 
# mean
mean = dfAge.mean(skipna = True, numeric_only= True) # DataFrame.mean() = sum / count
mean = mean.iloc[0] # to series.Series convertion
mean = round( mean, 2 ) 

# median
median = dfAge.median(skipna = True, numeric_only= True) # DataFrame.median() = devides a sorted array in halfs  
median = median.iloc[0] # to series.Series convertion
median = round( median, 2 ) 

# log
writeFile('4.txt', str( mean ) + ' ' + str( median ) )


In [7]:
# task 5: pearson correlation
# alretnative way: 
# dataframe: dataframe[['A','B']]

pearson = dataframe['SibSp'].corr(dataframe['Parch'])
writeFile('5.txt', round( pearson, 2 ))

In [3]:
# task 6: the most popular women name
dataframe[dataframe.Sex == 'female']

Survived  Pclass  \
PassengerId                     
2                   1       1   
3                   1       3   
4                   1       1   
9                   1       3   
10                  1       2   
...               ...     ...   
881                 1       2   
883                 0       3   
886                 0       3   
888                 1       1   
889                 0       3   

                                                          Name     Sex   Age  \
PassengerId                                                                    
2            Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
3                                       Heikkinen, Miss. Laina  female  26.0   
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0   
9            Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0   
10                         Nasser, Mrs. Nicholas (Adele Achem)  female  14.0   
...                                                        ...     ...   ...   
881               Shelley, Mrs. William (Imanita Parrish Hall)  female  25.0   
883                               Dahlberg, Miss. Gerda Ulrika  female  22.0   
886                       Rice, Mrs. William (Margaret Norton)  female  39.0   
888                               Graham, Miss. Margaret Edith  female  19.0   
889                   Johnston, Miss. Catherine Helen "Carrie"  female   NaN   

             SibSp  Parch            Ticket     Fare Cabin Embarked  
PassengerId                                                          
2                1      0          PC 17599  71.2833   C85        C  
3                0      0  STON/O2. 3101282   7.9250   NaN        S  
4                1      0            113803  53.1000  C123        S  
9                0      2            347742  11.1333   NaN        S  
10               1      0            237736  30.0708   NaN        C  
...            ...    ...               ...      ...   ...      ...  
881              0      1            230433  26.0000   NaN        S  
883              0      0              7552  10.5167   NaN        S  
886              0      5            382652  29.1250   NaN        Q  
888              0      0            112053  30.0000   B42        S  
889              1      2        W./C. 6607  23.4500   NaN        S  

[314 rows x 11 columns]